FROM centos:7

ENV TERM=xterm
ENV PLATFORM=""
ENV TAR_OPTIONS="--warning=no-timestamp"

# Fix repos since CentOS 7 is EOL
RUN rm -f /etc/yum.repos.d/*.repo && \
    printf "[base]\n\
name=CentOS-7 - Base\n\
baseurl=http://vault.centos.org/7.9.2009/os/x86_64/\n\
gpgcheck=0\n\
enabled=1\n\
\n\
[updates]\n\
name=CentOS-7 - Updates\n\
baseurl=http://vault.centos.org/7.9.2009/updates/x86_64/\n\
gpgcheck=0\n\
enabled=1\n\
\n\
[extras]\n\
name=CentOS-7 - Extras\n\
baseurl=http://vault.centos.org/7.9.2009/extras/x86_64/\n\
gpgcheck=0\n\
enabled=1\n" > /etc/yum.repos.d/CentOS-Vault.repo


RUN yum -y install epel-release && \
        yum -y install gcc \
        gcc-c++ \
        make \
        bc \
        git \
        ncurses-devel \
        openssl-devel \
        elfutils-libelf-devel \
        perl \
        wget \
        curl \
        jq \
        which \
        xz \
        bison \
        flex \
        pkgconfig \
        python3 \
        kmod \
        cifs-utils \
    && yum clean all

# Verify compiler versions (useful for debugging builds)
RUN gcc --version && ld --version

# Avoid warnings treated as errors in older kernels
ENV HOSTCFLAGS="-Wno-error"

RUN mkdir -p /synology-toolkit/toolchains
WORKDIR /synology-toolkit

COPY platforms.json .
COPY entrypoint.sh .
COPY config_modification.json .
COPY apply_patches.sh .

RUN chmod +x entrypoint.sh apply_patches.sh

ENTRYPOINT ["/synology-toolkit/entrypoint.sh"]